services:
  - type: web
    runtime: python
    name: em-posting
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /_stcore/health