[theme]
base = "light"
primaryColor = "#7057ff"
backgroundColor = "#f7f7f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#171a22"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 200
